spring:
  datasource:
    url: jdbc:sqlite:${user.home}/.ossflow/ossflow-dev.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  flyway:
    enabled: false
springdoc:
  swagger-ui:
    enabled: true
logging:
  level:
    com.ossflow: DEBUG
