spring:
  datasource:
    url: jdbc:sqlite:${OSSFLOW_DB_PATH:/data/ossflow.db}
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create
    show-sql: false
  flyway:
    enabled: false
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
