-- R__03_seed_techniques.sql
-- Técnicas BJJ del catálogo público (owner_id=1). Idempotente: ON CONFLICT DO NOTHING.
-- Consolida: V201-V206, V211 (belt fixes), V217 (extended).
-- Depende de: R__02_seed_positions.sql

-- =====================================================================
-- SUBMISSIONS (30)
-- =====================================================================
INSERT INTO technique (owner_id, name, category, description, minimum_belt, modality, start_position_id, end_position_id, visibility, created_at, updated_at, version)
VALUES
-- Chokes
(1, 'Rear Naked Choke',       'SUBMISSION', 'El estrangulamiento más importante del BJJ. Brazo rodeando el cuello con figura de 4. Ataca la arteria carótida.',                               'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Back Mount'                 AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Triangle Choke',         'SUBMISSION', 'Triángulo con las piernas atrapando cabeza y brazo del oponente. Estrangulación por compresión carotídea.',                                      'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Guillotine Choke',       'SUBMISSION', 'Estrangulación frontal con el brazo rodeando el cuello. Múltiples variantes: arm-in, high elbow, Marcelotine.',                                 'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Clinch'                     AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Bow and Arrow Choke',    'SUBMISSION', 'Estrangulación de espalda con grip en cuello y rodilla. La más efectiva desde back mount en gi.',                                                'BLUE',   'GI',   (SELECT id FROM position WHERE name='Back Mount'                 AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Cross Collar Choke',     'SUBMISSION', 'Doble grip en las solapas cruzando las muñecas contra el cuello. Clásico del gi desde mount y guardia.',                                        'WHITE',  'GI',   (SELECT id FROM position WHERE name='Full Mount'                 AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Baseball Bat Choke',     'SUBMISSION', 'Dos grips en el cuello en la misma dirección desde knee on belly o turtle. Gi. Rotación para aplicar.',                                         'BLUE',   'GI',   (SELECT id FROM position WHERE name='Knee On Belly'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'D''Arce Choke',          'SUBMISSION', 'Arm triangle con el brazo por debajo del cuello y sobre el brazo atrapado. Sin gi. Desde side control o turtle.',                               'BLUE',   'NOGI', (SELECT id FROM position WHERE name='Side Control'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Anaconda Choke',         'SUBMISSION', 'Inverso del D''Arce: brazo por encima del cuello. Ataque rodando desde turtle. Muy usado en competición.',                                      'BLUE',   'NOGI', (SELECT id FROM position WHERE name='Turtle Top'                 AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'North-South Choke',      'SUBMISSION', 'Estrangulación desde north-south usando el brazo y el peso corporal contra el cuello.',                                                          'BLUE',   'NOGI', (SELECT id FROM position WHERE name='North South'                AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Ezekiel Choke',          'SUBMISSION', 'Estrangulación usando la manga del gi o la muñeca desde mount. Se puede aplicar con el oponente en guardia cerrada.',                           'BLUE',   'GI',   (SELECT id FROM position WHERE name='Full Mount'                 AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Paper Cutter Choke',     'SUBMISSION', 'Estrangulación desde side control usando el antebrazo a través de la garganta con grip en el cuello lejano.',                                   'BLUE',   'GI',   (SELECT id FROM position WHERE name='Side Control'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Clock Choke',            'SUBMISSION', 'Estrangulación rotacional desde turtle: grip en el cuello lejano, rodar como las agujas del reloj.',                                            'BLUE',   'GI',   (SELECT id FROM position WHERE name='Turtle Top'                 AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Loop Choke',             'SUBMISSION', 'Estrangulación sorpresa desde guardia: un grip en el cuello con la cabeza bajo la axila. Gi.',                                                  'PURPLE', 'GI',   (SELECT id FROM position WHERE name='Closed Guard'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Peruvian Necktie',       'SUBMISSION', 'Variante de guillotine con las piernas sobre los hombros del oponente. Front headlock. Sin gi.',                                                'PURPLE', 'NOGI', (SELECT id FROM position WHERE name='Turtle Top'                 AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
-- Arm locks
(1, 'Armbar',                 'SUBMISSION', 'Hiperextensión del codo. El armbar más importante del BJJ. Aplicable desde mount, guardia, back mount y muchas otras posiciones.',               'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Kimura',                 'SUBMISSION', 'Llave de hombro con figura de 4 en el brazo. Aplicable desde side control, guardia, half guard y standing.',                                    'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Side Control'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Americana',              'SUBMISSION', 'Reverso del kimura. Empuja la muñeca hacia el suelo mientras levanta el codo. Desde side control y mount.',                                     'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Side Control'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Omoplata',               'SUBMISSION', 'Llave de hombro usando las piernas. La pierna atrapa el brazo y el cuerpo rota para aplicar la llave.',                                         'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Closed Guard'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Wristlock',              'SUBMISSION', 'Ataque a la articulación de la muñeca. Cuatro variantes: compresión, extensión, rotación interna y externa.',                                   'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Side Control'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Baratoplata',            'SUBMISSION', 'Llave de hombro tipo kimura usando piernas y caderas. Sigue a un triángulo. Popularizado por Braulio Estima.',                                  'BROWN',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Gogoplata',              'SUBMISSION', 'Omoplata con el pie en la garganta del oponente. Requiere gran flexibilidad. Sistema rubber guard.',                                             'BROWN',  'BOTH', (SELECT id FROM position WHERE name='Rubber Guard'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
-- Leg locks
(1, 'Straight Ankle Lock',    'SUBMISSION', 'Llave de tobillo recta: pie en la axila, caderas extendidas. Legal en todos los cinturones.',                                                   'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Single Leg X'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Inside Heel Hook',       'SUBMISSION', 'Torsión del talón hacia adentro atacando el ligamento externo de la rodilla. Legal desde brown belt IBJJF.',                                    'BROWN',  'NOGI', (SELECT id FROM position WHERE name='Single Leg X'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Outside Heel Hook',      'SUBMISSION', 'Torsión del talón hacia afuera. Ataca ligamentos internos de rodilla. El más peligroso de los leg locks.',                                      'BROWN',  'NOGI', (SELECT id FROM position WHERE name='Outside Heel Hook Position' AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Kneebar',                'SUBMISSION', 'Hiperextensión de la rodilla aislando la pierna entre el cuerpo. Ataque desde leg entanglement o mount.',                                       'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Leg Entanglement'           AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Toe Hold',               'SUBMISSION', 'Figura de 4 en el pie torciendo el tobillo/rodilla. Muy versátil desde cualquier leg entanglement.',                                            'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Leg Entanglement'           AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Calf Slicer',            'SUBMISSION', 'Compresión de gemelo: espinilla o antebrazo detrás de la rodilla doblando la pierna. Ilegal hasta purple belt.',                               'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Leg Entanglement'           AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Bicep Slicer',           'SUBMISSION', 'Compresión del bíceps: antebrazo o espinilla en el pliegue del codo. Ilegal hasta marrón en IBJJF.',                                           'BROWN',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Estima Lock',            'SUBMISSION', 'Foot lock atrapando el pie en el pliegue del codo. Creado por Victor Estima. Desde guardia cerrada.',                                          'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Closed Guard'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Electric Chair',         'SUBMISSION', 'Stretch desde lockdown half guard. Ataca ingle y aductores. Sistema 10th Planet de Eddie Bravo.',                                              'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Lockdown'                   AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
ON CONFLICT DO NOTHING;

-- =====================================================================
-- SWEEPS (18)
-- =====================================================================
INSERT INTO technique (owner_id, name, category, description, minimum_belt, modality, start_position_id, end_position_id, visibility, created_at, updated_at, version)
VALUES
(1, 'Scissor Sweep',           'SWEEP', 'Movimiento en tijera desde guardia cerrada. Se carga al oponente en la rodilla y se hace palanca con las piernas en oposición.',                'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Hip Bump Sweep',          'SWEEP', 'Explosión de cadera desde guardia cerrada. Se sienta hacia adelante usando el momentum de cadera para voltear.',                               'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Flower Sweep',            'SWEEP', 'Barrido pendular desde guardia cerrada. Grip en manga y pantalón, movimiento pendular de la pierna libre para voltear.',                       'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Butterfly Sweep',         'SWEEP', 'Barrido con ganchos mariposa. Underhook + gancho del pie para levantar y voltear. Muy efectivo en no-gi.',                                    'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Butterfly Guard'  AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Elevator Sweep',          'SWEEP', 'Barrido desde half guard usando el gancho interior como ascensor para levantar la pierna del oponente.',                                       'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Old School Sweep',        'SWEEP', 'Sweep clásico desde half guard: underhook, control del pie, sacar el pie y rodar. Muy básico y efectivo.',                                    'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'De La Riva Sweep',        'SWEEP', 'Barrido clásico desde DLR: empujar con el pie del gancho, tirar del tobillo, rodar hacia el lado contrario.',                                 'BLUE',   'GI',   (SELECT id FROM position WHERE name='De La Riva Guard' AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Spider Guard Sweep',      'SWEEP', 'Barrido desde spider guard: empujar un bíceps con el pie mientras se jala la manga contraria para desequilibrar.',                            'BLUE',   'GI',   (SELECT id FROM position WHERE name='Spider Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'X-Guard Sweep',           'SWEEP', 'Elevación desde X-guard para tirar al oponente hacia atrás o lateral. Technical stand o proyección.',                                         'BLUE',   'BOTH', (SELECT id FROM position WHERE name='X-Guard'          AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Single Leg X Sweep',      'SWEEP', 'Barrido desde ashi garami/SLX. Múltiples variantes: back sweep, outside sweep, technical stand.',                                             'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Single Leg X'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Lasso Pendulum Sweep',    'SWEEP', 'Combinación de lasso guard y movimiento pendular para voltear al oponente. Solo gi.',                                                          'BLUE',   'GI',   (SELECT id FROM position WHERE name='Lasso Guard'      AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Berimbolo Back Take',     'SWEEP', 'Inversión desde DLR para rodar por debajo y tomar la espalda. Movimiento icónico del BJJ moderno.',                                           'PURPLE', 'GI',   (SELECT id FROM position WHERE name='De La Riva Guard' AND owner_id=1), (SELECT id FROM position WHERE name='Back Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Deep Half Sweep',         'SWEEP', 'Barrido desde deep half guard pasando por debajo para voltear al oponente y quedar encima.',                                                   'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Deep Half Guard'  AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Waiter Sweep',            'SWEEP', 'Sweep desde half guard inspirado en el gesto de mesero: elevar la pierna del oponente con el pie interior.',                                   'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'John Wayne Sweep',        'SWEEP', 'Sweep desde half guard estirando la pierna del oponente lateralmente. Variante del sistema de half guard.',                                    'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Tripod Sweep',            'SWEEP', 'Barrido desde open guard: un pie en la cadera, otro enganchando el tobillo, jalando la manga hacia abajo.',                                   'WHITE',  'GI',   (SELECT id FROM position WHERE name='Seated Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Sickle Sweep',            'SWEEP', 'Variante del tripod sweep con el pie barriendo el tobillo del oponente en arco. Desde seated guard.',                                         'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Seated Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Knee Shield Sweep',       'SWEEP', 'Sweep desde Z-guard usando el escudo de rodilla para crear distancia y voltear con underhook.',                                                'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Z-Guard'          AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
ON CONFLICT DO NOTHING;

-- =====================================================================
-- PASSES (18)
-- =====================================================================
INSERT INTO technique (owner_id, name, category, description, minimum_belt, modality, start_position_id, end_position_id, visibility, created_at, updated_at, version)
VALUES
(1, 'Torreando Pass',          'PASS', 'Pase de velocidad jalando ambas piernas a un lado y pasando rápidamente a side control. El más fundamental del BJJ.',                           'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Seated Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Knee Slice Pass',         'PASS', 'La rodilla corta diagonalmente el muslo del oponente. El pase más versátil y de mayor porcentaje en gi y no-gi.',                              'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Leg Drag Pass',           'PASS', 'Arrastra la pierna del oponente cruzando su cadera. Connector entre passing externo y passing de presión.',                                    'BLUE',   'BOTH', (SELECT id FROM position WHERE name='De La Riva Guard' AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Over-Under Pass',         'PASS', 'Un brazo por encima de una pierna, otro por debajo de la otra. Presión máxima sobre las caderas del oponente.',                                'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Double Under Pass',       'PASS', 'Ambos brazos por debajo de ambas piernas. Stack y presión hacia la cabeza del oponente para pasar.',                                           'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Smash Pass',              'PASS', 'Pase de presión aplastando las piernas del oponente con el peso corporal. No-gi. Muy popular en competición.',                                 'BLUE',   'NOGI', (SELECT id FROM position WHERE name='Butterfly Guard'  AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Body Lock Pass',          'PASS', 'Abrazo de caderas cerrado (no-gi). El estándar del high-level no-gi moderno. Dominado por Gordon Ryan.',                                       'PURPLE', 'NOGI', (SELECT id FROM position WHERE name='Seated Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'X-Pass',                  'PASS', 'Control rápido de una rodilla y cadera para pasar. Velocidad y timing antes que fuerza.',                                                      'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Seated Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Long Step Pass',          'PASS', 'Paso largo hacia atrás para liberar la pierna de la guardia y pasar. Efectivo contra guardia cerrada y media guardia.',                        'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Float Pass',              'PASS', 'Pase flotante usando timing y equilibrio sin presionar. Popularizado por Danaher/Gordon Ryan contra guardias pegajosas.',                      'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='De La Riva Guard' AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Backstep Pass',           'PASS', 'Paso atrás sobre la pierna del oponente para pasar. Muy efectivo contra DLR y guardias abiertas.',                                             'BLUE',   'BOTH', (SELECT id FROM position WHERE name='De La Riva Guard' AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Running Pass',            'PASS', 'Rueda lateral o carrera alrededor de la guardia del oponente. Requiere espacio y velocidad.',                                                   'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Spider Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Half Guard Pass',         'PASS', 'Pase de media guardia usando crossface y presión para liberar la pierna atrapada.',                                                             'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Leg Weave Pass',          'PASS', 'Teje el brazo debajo de la pierna conectando al cuello. Pase de presión desde closed guard y half guard.',                                     'BLUE',   'GI',   (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Sao Paulo Pass',          'PASS', 'Pase gi usando el lapel cruzado por debajo de la pierna para fijarla. Variante del over-under.',                                               'PURPLE', 'GI',   (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Torreando to Mount',      'PASS', 'Variante del torreando que termina directamente en mount saltando la fase de side control.',                                                    'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Seated Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'   AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Shin Slide Pass',         'PASS', 'Espinilla deslizando sobre el muslo del oponente para pasar. Variante del knee slice.',                                                        'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Wilson Pass',             'PASS', 'Pase de presión usando el hombro en la cadera del oponente. Grinding y lento pero muy efectivo.',                                              'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
ON CONFLICT DO NOTHING;

-- =====================================================================
-- TAKEDOWNS (12)
-- =====================================================================
INSERT INTO technique (owner_id, name, category, description, minimum_belt, modality, start_position_id, end_position_id, visibility, created_at, updated_at, version)
VALUES
(1, 'Double Leg Takedown',    'TAKEDOWN', 'Derribo de lucha libre clásico: agarre de ambas piernas, empuje con el hombro en la cadera.',                                           'WHITE', 'BOTH', (SELECT id FROM position WHERE name='Standing Neutral'  AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Single Leg Takedown',    'TAKEDOWN', 'Derribo agarrando una sola pierna. Múltiples variantes de terminación: run the pipe, high crotch, trip.',                              'WHITE', 'BOTH', (SELECT id FROM position WHERE name='Standing Neutral'  AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Ankle Pick',             'TAKEDOWN', 'Derribo de bajo riesgo: jalar el tobillo mientras se empuja el hombro. Muy común en BJJ por su seguridad.',                            'WHITE', 'BOTH', (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Arm Drag to Back Take',  'TAKEDOWN', 'Arrastre de brazo de pie para tomar la espalda de pie o llevar al suelo en back mount.',                                               'WHITE', 'BOTH', (SELECT id FROM position WHERE name='Arm Drag Position' AND owner_id=1), (SELECT id FROM position WHERE name='Back Mount'   AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Hip Throw',              'TAKEDOWN', 'Proyección de judo básica usando la cadera como pivote (O-Goshi). La más enseñada a principiantes.',                                   'WHITE', 'BOTH', (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Shoulder Throw',         'TAKEDOWN', 'Proyección de hombro de judo (Seoi Nage). Muy efectiva cuando el oponente empuja. Gi y no-gi.',                                        'BLUE',  'BOTH', (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Harai Goshi',            'TAKEDOWN', 'Proyección de judo barriendo la cadera del oponente. Una de las proyecciones más antiguas del Kodokan.',                               'BLUE',  'GI',   (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Foot Sweep',             'TAKEDOWN', 'Barrido de pie interno (O-Uchi Gari). Derribo de bajo riesgo muy usado en BJJ. Funciona en gi y no-gi.',                              'WHITE', 'BOTH', (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Kouchi Gari',            'TAKEDOWN', 'Barrido de pie menor interno. Barre el pie delantero del oponente hacia adentro.',                                                     'BLUE',  'GI',   (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Snap Down',              'TAKEDOWN', 'Snap del cuello hacia abajo para hacer turtle al oponente. Base para guillotina o anaconda.',                                          'WHITE', 'NOGI', (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Turtle Top'   AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Sacrifice Throw',        'TAKEDOWN', 'Proyección de sacrificio (Tomoe Nage): caer de espaldas y proyectar al oponente por encima. Gi. Alto riesgo/recompensa.',             'BLUE',  'GI',   (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'   AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Guard Pull',             'TAKEDOWN', 'Sentarse a guardia intencionalmente. Técnica controvertida pero muy usada en competición de gi.',                                       'WHITE', 'GI',   (SELECT id FROM position WHERE name='Standing Neutral'  AND owner_id=1), (SELECT id FROM position WHERE name='Closed Guard' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
ON CONFLICT DO NOTHING;

-- =====================================================================
-- ESCAPES (12)
-- =====================================================================
INSERT INTO technique (owner_id, name, category, description, minimum_belt, modality, start_position_id, end_position_id, visibility, created_at, updated_at, version)
VALUES
(1, 'Bridge and Roll',            'ESCAPE', 'Puente y rodillo desde bottom mount (Upa). Bridge explosivo al lado donde el brazo está atrapado para volcar.',                         'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Bottom Mount'           AND owner_id=1), (SELECT id FROM position WHERE name='Closed Guard'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Elbow-Knee Escape',          'ESCAPE', 'Escape codo-rodilla desde mount usando el movimiento de gambas (shrimp). Recupera guardia media o cerrada.',                            'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Bottom Mount'           AND owner_id=1), (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Side Control Knee-In',       'ESCAPE', 'Insertar la rodilla desde bottom side control usando bridge+shrimp. Recuperar guardia es la clave.',                                    'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Bottom Side Control'    AND owner_id=1), (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Ghost Escape',               'ESCAPE', 'Escapar hacia atrás desde side control como fantasma: rodar el hombro por debajo del oponente.',                                       'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Bottom Side Control'    AND owner_id=1), (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Back Escape',                'ESCAPE', 'Escapar del back mount: bajar el gancho superior, defender el cuello con dos manos y rodar hacia un lado.',                            'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Bottom Back Mount'      AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Turtle Guard Recovery',      'ESCAPE', 'Rodar desde turtle para recuperar guardia. Múltiples opciones: rodar adelante, atrás o lateral.',                                      'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Turtle'                 AND owner_id=1), (SELECT id FROM position WHERE name='Closed Guard'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'North-South Escape',         'ESCAPE', 'Escapar desde north-south: girar los hombros y recuperar guardia lateral o media guardia.',                                            'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Bottom Side Control'    AND owner_id=1), (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Kimura Defense to Guard',    'ESCAPE', 'Defender kimura desde side control y convertirla en oportunidad de recuperar guardia.',                                                'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Bottom Side Control'    AND owner_id=1), (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Knee On Belly Escape',       'ESCAPE', 'Escapar de knee on belly: crear espacio, introducir guardia o rodar hacia los pies del oponente.',                                     'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Bottom Knee On Belly'   AND owner_id=1), (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Armbar Defense',             'ESCAPE', 'Defender el armbar: stacking, voltear, interlazar los dedos. Recuperar guardia o posición top.',                                      'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'           AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Triangle Defense',           'ESCAPE', 'Defender el triángulo: stack + postura, voltear, salir hacia el pasador.',                                                            'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'           AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Heel Hook Defense',          'ESCAPE', 'Defensa urgente de heel hook: no rotar, alinear rodilla, escape vine o back step.',                                                   'PURPLE', 'NOGI', (SELECT id FROM position WHERE name='Leg Entanglement'       AND owner_id=1), (SELECT id FROM position WHERE name='Standing Neutral'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
ON CONFLICT DO NOTHING;

-- =====================================================================
-- TRANSITIONS (12)
-- =====================================================================
INSERT INTO technique (owner_id, name, category, description, minimum_belt, modality, start_position_id, end_position_id, visibility, created_at, updated_at, version)
VALUES
(1, 'Mount to Back Take',          'TRANSITION', 'Tomar la espalda desde mount cuando el oponente se voltea intentando escapar. Seguir el movimiento.',                             'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Full Mount'         AND owner_id=1), (SELECT id FROM position WHERE name='Back Mount'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Side Control to Mount',       'TRANSITION', 'Avanzar de side control a mount: knee slide, step over o técnica de rodilla.',                                                   'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Side Control'       AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Side Control to Back Take',   'TRANSITION', 'Tomar la espalda desde side control cuando el oponente se voltea hacia la turtle.',                                              'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Side Control'       AND owner_id=1), (SELECT id FROM position WHERE name='Back Mount'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Guard to Back Take',          'TRANSITION', 'Transición de cualquier guardia a toma de espalda. Desde closed guard, butterfly, X-guard.',                                     'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Closed Guard'       AND owner_id=1), (SELECT id FROM position WHERE name='Back Mount'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Side Control to North-South', 'TRANSITION', 'Girar de side control a north-south para cambiar ángulo de ataque o presión.',                                                   'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Side Control'       AND owner_id=1), (SELECT id FROM position WHERE name='North South'     AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'DLR to Single Leg X',         'TRANSITION', 'Transición de DLR a SLX (ashi garami). Girar por debajo para re-enredar la pierna.',                                            'BLUE',   'BOTH', (SELECT id FROM position WHERE name='De La Riva Guard'   AND owner_id=1), (SELECT id FROM position WHERE name='Single Leg X'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Half Guard to Deep Half',     'TRANSITION', 'Hundirse bajo el oponente desde media guardia para llegar a deep half guard.',                                                   'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Half Guard'         AND owner_id=1), (SELECT id FROM position WHERE name='Deep Half Guard' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Closed Guard to Butterfly',   'TRANSITION', 'Abrir la guardia cerrada y reconfigurar los ganchos para guardia mariposa.',                                                    'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'       AND owner_id=1), (SELECT id FROM position WHERE name='Butterfly Guard' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Mount to Knee On Belly',      'TRANSITION', 'Pasar de mount a knee on belly para cambiar el ángulo o presionar diferente.',                                                  'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Full Mount'         AND owner_id=1), (SELECT id FROM position WHERE name='Knee On Belly'   AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'North-South to Kimura Trap',  'TRANSITION', 'Desde north-south entrar al kimura trap para controlar el brazo y avanzar a mount o back.',                                     'BLUE',   'BOTH', (SELECT id FROM position WHERE name='North South'        AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Ashi Garami to 50/50',        'TRANSITION', 'Desde ashi garami básico el oponente gira para crear la posición 50/50 simétrica.',                                             'PURPLE', 'NOGI', (SELECT id FROM position WHERE name='Single Leg X'       AND owner_id=1), (SELECT id FROM position WHERE name='50/50'            AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Turtle to Guard Recovery',    'TRANSITION', 'Desde turtle rodar hacia adelante para recuperar guardia antes de que el oponente tome la espalda.',                            'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Turtle'             AND owner_id=1), (SELECT id FROM position WHERE name='Closed Guard'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
ON CONFLICT DO NOTHING;
