-- V201__seed_techniques_submissions.sql
-- 30 submissions curadas (owner_id=1, visibilidad pública)
-- Requiere V200__seed_positions.sql ejecutado primero.

INSERT INTO technique (owner_id, name, category, description, minimum_belt, modality, start_position_id, end_position_id, visibility, created_at, updated_at, version) VALUES

-- CHOKES
(1, 'Rear Naked Choke',       'SUBMISSION', 'El estrangulamiento más importante del BJJ. Brazo rodeando el cuello con figura de 4. Ataca la arteria carótida.',                               'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Back Mount'                AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Triangle Choke',         'SUBMISSION', 'Triángulo con las piernas atrapando cabeza y brazo del oponente. Estrangulación por compresión carotídea.',                                      'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Guillotine Choke',       'SUBMISSION', 'Estrangulación frontal con el brazo rodeando el cuello. Múltiples variantes: arm-in, high elbow, Marcelotine.',                                 'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Clinch'                    AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Bow and Arrow Choke',    'SUBMISSION', 'Estrangulación de espalda con grip en cuello y rodilla. La más efectiva desde back mount en gi.',                                                'BLUE',   'GI',   (SELECT id FROM position WHERE name='Back Mount'                AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Cross Collar Choke',     'SUBMISSION', 'Doble grip en las solapas cruzando las muñecas contra el cuello. Clásico del gi desde mount y guardia.',                                        'WHITE',  'GI',   (SELECT id FROM position WHERE name='Full Mount'                AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Baseball Bat Choke',     'SUBMISSION', 'Dos grips en el cuello en la misma dirección desde knee on belly o turtle. Gi. Rotación para aplicar.',                                         'BLUE',   'GI',   (SELECT id FROM position WHERE name='Knee On Belly'             AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'D''Arce Choke',          'SUBMISSION', 'Arm triangle con el brazo por debajo del cuello y sobre el brazo atrapado. Sin gi. Desde side control o turtle.',                               'BLUE',   'NOGI', (SELECT id FROM position WHERE name='Side Control'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Anaconda Choke',         'SUBMISSION', 'Inverso del D''Arce: brazo por encima del cuello. Ataque rodando desde turtle. Muy usado en competición.',                                      'BLUE',   'NOGI', (SELECT id FROM position WHERE name='Turtle Top'                AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'North-South Choke',      'SUBMISSION', 'Estrangulación desde north-south usando el brazo y el peso corporal contra el cuello.',                                                          'BLUE',   'NOGI', (SELECT id FROM position WHERE name='North South'               AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Ezekiel Choke',          'SUBMISSION', 'Estrangulación usando la manga del gi o la muñeca desde mount. Se puede aplicar con el oponente en guardia cerrada.',                           'BLUE',   'GI',   (SELECT id FROM position WHERE name='Full Mount'                AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Paper Cutter Choke',     'SUBMISSION', 'Estrangulación desde side control usando el antebrazo a través de la garganta con grip en el cuello lejano.',                                   'BLUE',   'GI',   (SELECT id FROM position WHERE name='Side Control'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Clock Choke',            'SUBMISSION', 'Estrangulación rotacional desde turtle: grip en el cuello lejano, rodar como las agujas del reloj.',                                            'BLUE',   'GI',   (SELECT id FROM position WHERE name='Turtle Top'                AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Loop Choke',             'SUBMISSION', 'Estrangulación sorpresa desde guardia: un grip en el cuello con la cabeza bajo la axila. Gi.',                                                  'PURPLE', 'GI',   (SELECT id FROM position WHERE name='Closed Guard'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Peruvian Necktie',       'SUBMISSION', 'Variante de guillotine con las piernas sobre los hombros del oponente. Front headlock. Sin gi.',                                                'PURPLE', 'NOGI', (SELECT id FROM position WHERE name='Turtle Top'                AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),

-- ARM LOCKS
(1, 'Armbar',                 'SUBMISSION', 'Hiperextensión del codo. El armbar más importante del BJJ. Aplicable desde mount, guardia, back mount y muchas otras posiciones.',               'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Kimura',                 'SUBMISSION', 'Llave de hombro con figura de 4 en el brazo. Aplicable desde side control, guardia, half guard y standing.',                                    'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Side Control'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Americana',              'SUBMISSION', 'Reverso del kimura. Empuja la muñeca hacia el suelo mientras levanta el codo. Desde side control y mount.',                                     'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Side Control'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Omoplata',               'SUBMISSION', 'Llave de hombro usando las piernas. La pierna atrapa el brazo y el cuerpo rota para aplicar la llave.',                                         'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Closed Guard'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Wristlock',              'SUBMISSION', 'Ataque a la articulación de la muñeca. Cuatro variantes: compresión, extensión, rotación interna y externa.',                                   'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Side Control'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Baratoplata',            'SUBMISSION', 'Llave de hombro tipo kimura usando piernas y caderas. Sigue a un triángulo. Popularizado por Braulio Estima.',                                  'BROWN',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Gogoplata',              'SUBMISSION', 'Omoplata con el pie en la garganta del oponente. Requiere gran flexibilidad. Sistema rubber guard.',                                             'BROWN',  'BOTH', (SELECT id FROM position WHERE name='Rubber Guard'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),

-- LEG LOCKS
(1, 'Straight Ankle Lock',    'SUBMISSION', 'Llave de tobillo recta: pie en la axila, caderas extendidas. Legal en todos los cinturones.',                                                   'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Single Leg X'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Inside Heel Hook',       'SUBMISSION', 'Torsión del talón hacia adentro atacando el ligamento externo de la rodilla. Legal desde brown belt IBJJF.',                                    'BROWN',  'NOGI', (SELECT id FROM position WHERE name='Single Leg X'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Outside Heel Hook',      'SUBMISSION', 'Torsión del talón hacia afuera. Ataca ligamentos internos de rodilla. El más peligroso de los leg locks.',                                      'BROWN',  'NOGI', (SELECT id FROM position WHERE name='Outside Heel Hook Position' AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Kneebar',                'SUBMISSION', 'Hiperextensión de la rodilla aislando la pierna entre el cuerpo. Ataque desde leg entanglement o mount.',                                       'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Leg Entanglement'          AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Toe Hold',               'SUBMISSION', 'Figura de 4 en el pie torciendo el tobillo/rodilla. Muy versátil desde cualquier leg entanglement.',                                            'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Leg Entanglement'          AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Calf Slicer',            'SUBMISSION', 'Compresión de gemelo: espinilla o antebrazo detrás de la rodilla doblando la pierna. Ilegal hasta purple belt.',                               'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Leg Entanglement'          AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Bicep Slicer',           'SUBMISSION', 'Compresión del bíceps: antebrazo o espinilla en el pliegue del codo. Ilegal hasta marrón en IBJJF.',                                           'BROWN',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Estima Lock',            'SUBMISSION', 'Foot lock atrapando el pie en el pliegue del codo. Creado por Victor Estima. Desde guardia cerrada.',                                          'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Closed Guard'              AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Electric Chair',         'SUBMISSION', 'Stretch desde lockdown half guard. Ataca ingle y aductores. Sistema 10th Planet de Eddie Bravo.',                                              'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Lockdown'                  AND owner_id=1), (SELECT id FROM position WHERE name='Submitted' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
