-- V202__seed_techniques_sweeps.sql
-- 18 barridos curados (owner_id=1, visibilidad pública)

INSERT INTO technique (owner_id, name, category, description, minimum_belt, modality, start_position_id, end_position_id, visibility, created_at, updated_at, version) VALUES

(1, 'Scissor Sweep',           'SWEEP', 'Movimiento en tijera desde guardia cerrada. Se carga al oponente en la rodilla y se hace palanca con las piernas en oposición.',                'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Hip Bump Sweep',          'SWEEP', 'Explosión de cadera desde guardia cerrada. Se sienta hacia adelante usando el momentum de cadera para voltear.',                               'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Flower Sweep',            'SWEEP', 'Barrido pendular desde guardia cerrada. Grip en manga y pantalón, movimiento pendular de la pierna libre para voltear.',                       'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Butterfly Sweep',         'SWEEP', 'Barrido con ganchos mariposa. Underhook + gancho del pie para levantar y voltear. Muy efectivo en no-gi.',                                    'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Butterfly Guard'  AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Elevator Sweep',          'SWEEP', 'Barrido desde half guard usando el gancho interior como ascensor para levantar la pierna del oponente.',                                       'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Old School Sweep',        'SWEEP', 'Sweep clásico desde half guard: underhook, control del pie, sacar el pie y rodar. Muy básico y efectivo.',                                    'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'De La Riva Sweep',        'SWEEP', 'Barrido clásico desde DLR: empujar con el pie del gancho, tirar del tobillo, rodar hacia el lado contrario.',                                 'BLUE',   'GI',   (SELECT id FROM position WHERE name='De La Riva Guard' AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Spider Guard Sweep',      'SWEEP', 'Barrido desde spider guard: empujar un bíceps con el pie mientras se jala la manga contraria para desequilibrar.',                            'BLUE',   'GI',   (SELECT id FROM position WHERE name='Spider Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'X-Guard Sweep',           'SWEEP', 'Elevación desde X-guard para tirar al oponente hacia atrás o lateral. Technical stand o proyección.',                                         'BLUE',   'BOTH', (SELECT id FROM position WHERE name='X-Guard'          AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Single Leg X Sweep',      'SWEEP', 'Barrido desde ashi garami/SLX. Múltiples variantes: back sweep, outside sweep, technical stand.',                                             'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Single Leg X'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Lasso Pendulum Sweep',    'SWEEP', 'Combinación de lasso guard y movimiento pendular para voltear al oponente. Solo gi.',                                                          'BLUE',   'GI',   (SELECT id FROM position WHERE name='Lasso Guard'      AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Berimbolo Back Take',     'SWEEP', 'Inversión desde DLR para rodar por debajo y tomar la espalda. Movimiento icónico del BJJ moderno.',                                           'PURPLE', 'GI',   (SELECT id FROM position WHERE name='De La Riva Guard' AND owner_id=1), (SELECT id FROM position WHERE name='Back Mount'    AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Deep Half Sweep',         'SWEEP', 'Barrido desde deep half guard pasando por debajo para voltear al oponente y quedar encima.',                                                   'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Deep Half Guard'  AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Waiter Sweep',            'SWEEP', 'Sweep desde half guard inspirado en el gesto de mesero: elevar la pierna del oponente con el pie interior.',                                   'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'John Wayne Sweep',        'SWEEP', 'Sweep desde half guard estirando la pierna del oponente lateralmente. Variante del sistema de half guard.',                                    'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Tripod Sweep',            'SWEEP', 'Barrido desde open guard: un pie en la cadera, otro enganchando el tobillo, jalando la manga hacia abajo.',                                   'WHITE',  'GI',   (SELECT id FROM position WHERE name='Seated Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Sickle Sweep',            'SWEEP', 'Variante del tripod sweep con el pie barriendo el tobillo del oponente en arco. Desde seated guard.',                                         'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Seated Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Knee Shield Sweep',       'SWEEP', 'Sweep desde Z-guard usando el escudo de rodilla para crear distancia y voltear con underhook.',                                                'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Z-Guard'          AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
