-- V203__seed_techniques_passes.sql
-- 18 pases de guardia curados (owner_id=1, visibilidad pública)

INSERT INTO technique (owner_id, name, category, description, minimum_belt, modality, start_position_id, end_position_id, visibility, created_at, updated_at, version) VALUES

(1, 'Torreando Pass',          'PASS', 'Pase de velocidad jalando ambas piernas a un lado y pasando rápidamente a side control. El más fundamental del BJJ.',                           'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Seated Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Knee Slice Pass',         'PASS', 'La rodilla corta diagonalmente el muslo del oponente. El pase más versátil y de mayor porcentaje en gi y no-gi.',                              'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Leg Drag Pass',           'PASS', 'Arrastra la pierna del oponente cruzando su cadera. Connector entre passing externo y passing de presión.',                                    'BLUE',   'BOTH', (SELECT id FROM position WHERE name='De La Riva Guard' AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Over-Under Pass',         'PASS', 'Un brazo por encima de una pierna, otro por debajo de la otra. Presión máxima sobre las caderas del oponente.',                                'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Double Under Pass',       'PASS', 'Ambos brazos por debajo de ambas piernas. Stack y presión hacia la cabeza del oponente para pasar.',                                           'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Smash Pass',              'PASS', 'Pase de presión aplastando las piernas del oponente con el peso corporal. No-gi. Muy popular en competición.',                                 'BLUE',   'NOGI', (SELECT id FROM position WHERE name='Butterfly Guard'  AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Body Lock Pass',          'PASS', 'Abrazo de caderas cerrado (no-gi). El estándar del high-level no-gi moderno. Dominado por Gordon Ryan.',                                       'PURPLE', 'NOGI', (SELECT id FROM position WHERE name='Seated Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'X-Pass',                  'PASS', 'Control rápido de una rodilla y cadera para pasar. Velocidad y timing antes que fuerza.',                                                      'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Seated Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Long Step Pass',          'PASS', 'Paso largo hacia atrás para liberar la pierna de la guardia y pasar. Efectivo contra guardia cerrada y media guardia.',                        'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Float Pass',              'PASS', 'Pase flotante usando timing y equilibrio sin presionar. Popularizado por Danaher/Gordon Ryan contra guardias pegajosas.',                      'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='De La Riva Guard' AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Backstep Pass',           'PASS', 'Paso atrás sobre la pierna del oponente para pasar. Muy efectivo contra DLR y guardias abiertas.',                                             'BLUE',   'BOTH', (SELECT id FROM position WHERE name='De La Riva Guard' AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Running Pass',            'PASS', 'Rueda lateral o carrera alrededor de la guardia del oponente. Requiere espacio y velocidad.',                                                   'PURPLE', 'BOTH', (SELECT id FROM position WHERE name='Spider Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Half Guard Pass',         'PASS', 'Pase de media guardia usando crossface y presión para liberar la pierna atrapada.',                                                             'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Leg Weave Pass',          'PASS', 'Teje el brazo debajo de la pierna conectando al cuello. Pase de presión desde closed guard y half guard.',                                     'BLUE',   'GI',   (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Sao Paulo Pass',          'PASS', 'Pase gi usando el lapel cruzado por debajo de la pierna para fijarla. Variante del over-under.',                                               'PURPLE', 'GI',   (SELECT id FROM position WHERE name='Closed Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Torreando to Mount',      'PASS', 'Variante del torreando que termina directamente en mount saltando la fase de side control.',                                                    'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Seated Guard'     AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'   AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Shin Slide Pass',         'PASS', 'Espinilla deslizando sobre el muslo del oponente para pasar. Variante del knee slice.',                                                        'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Wilson Pass',             'PASS', 'Pase de presión usando el hombro en la cadera del oponente. Grinding y lento pero muy efectivo.',                                              'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
