-- V204__seed_techniques_takedowns.sql
-- 12 derribos curados (owner_id=1, visibilidad pública)

INSERT INTO technique (owner_id, name, category, description, minimum_belt, modality, start_position_id, end_position_id, visibility, created_at, updated_at, version) VALUES

(1, 'Double Leg Takedown',    'TAKEDOWN', 'Derribo de lucha libre clásico: agarre de ambas piernas, empuje con el hombro en la cadera.',                                           'WHITE', 'BOTH', (SELECT id FROM position WHERE name='Standing Neutral'  AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Single Leg Takedown',    'TAKEDOWN', 'Derribo agarrando una sola pierna. Múltiples variantes de terminación: run the pipe, high crotch, trip.',                              'WHITE', 'BOTH', (SELECT id FROM position WHERE name='Standing Neutral'  AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Ankle Pick',             'TAKEDOWN', 'Derribo de bajo riesgo: jalar el tobillo mientras se empuja el hombro. Muy común en BJJ por su seguridad.',                            'WHITE', 'BOTH', (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Arm Drag to Back Take',  'TAKEDOWN', 'Arrastre de brazo de pie para tomar la espalda de pie o llevar al suelo en back mount.',                                               'WHITE', 'BOTH', (SELECT id FROM position WHERE name='Arm Drag Position' AND owner_id=1), (SELECT id FROM position WHERE name='Back Mount'   AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Hip Throw',              'TAKEDOWN', 'Proyección de judo básica usando la cadera como pivote (O-Goshi). La más enseñada a principiantes.',                                   'WHITE', 'BOTH', (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Shoulder Throw',         'TAKEDOWN', 'Proyección de hombro de judo (Seoi Nage). Muy efectiva cuando el oponente empuja. Gi y no-gi.',                                        'BLUE',  'BOTH', (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Harai Goshi',            'TAKEDOWN', 'Proyección de judo barriendo la cadera del oponente. Una de las proyecciones más antiguas del Kodokan.',                               'BLUE',  'GI',   (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Foot Sweep',             'TAKEDOWN', 'Barrido de pie interno (O-Uchi Gari). Derribo de bajo riesgo muy usado en BJJ. Funciona en gi y no-gi.',                              'WHITE', 'BOTH', (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Kouchi Gari',            'TAKEDOWN', 'Barrido de pie menor interno. Barre el pie delantero del oponente hacia adentro.',                                                     'BLUE',  'GI',   (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Side Control' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Snap Down',              'TAKEDOWN', 'Snap del cuello hacia abajo para hacer turtle al oponente. Base para guillotina o anaconda.',                                          'WHITE', 'NOGI', (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Turtle Top'   AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Sacrifice Throw',        'TAKEDOWN', 'Proyección de sacrificio (Tomoe Nage): caer de espaldas y proyectar al oponente por encima. Gi. Alto riesgo/recompensa.',             'BLUE',  'GI',   (SELECT id FROM position WHERE name='Clinch'            AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'   AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Guard Pull',             'TAKEDOWN', 'Sentarse a guardia intencionalmente. Técnica controvertida pero muy usada en competición de gi.',                                       'WHITE', 'GI',   (SELECT id FROM position WHERE name='Standing Neutral'  AND owner_id=1), (SELECT id FROM position WHERE name='Closed Guard' AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
