-- V205__seed_techniques_escapes.sql
-- 12 escapes curados (owner_id=1, visibilidad pública)

INSERT INTO technique (owner_id, name, category, description, minimum_belt, modality, start_position_id, end_position_id, visibility, created_at, updated_at, version) VALUES

(1, 'Bridge and Roll',            'ESCAPE', 'Puente y rodillo desde bottom mount (Upa). Bridge explosivo al lado donde el brazo está atrapado para volcar.',                         'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Bottom Mount'           AND owner_id=1), (SELECT id FROM position WHERE name='Closed Guard'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Elbow-Knee Escape',          'ESCAPE', 'Escape codo-rodilla desde mount usando el movimiento de gambas (shrimp). Recupera guardia media o cerrada.',                            'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Bottom Mount'           AND owner_id=1), (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Side Control Knee-In',       'ESCAPE', 'Insertar la rodilla desde bottom side control usando bridge+shrimp. Recuperar guardia es la clave.',                                    'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Bottom Side Control'    AND owner_id=1), (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Ghost Escape',               'ESCAPE', 'Escapar hacia atrás desde side control como fantasma: rodar el hombro por debajo del oponente.',                                       'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Bottom Side Control'    AND owner_id=1), (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Back Escape',                'ESCAPE', 'Escapar del back mount: bajar el gancho superior, defender el cuello con dos manos y rodar hacia un lado.',                            'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Bottom Back Mount'      AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Turtle Guard Recovery',      'ESCAPE', 'Rodar desde turtle para recuperar guardia. Múltiples opciones: rodar adelante, atrás o lateral.',                                      'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Turtle'                 AND owner_id=1), (SELECT id FROM position WHERE name='Closed Guard'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'North-South Escape',         'ESCAPE', 'Escapar desde north-south: girar los hombros y recuperar guardia lateral o media guardia.',                                            'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Bottom Side Control'    AND owner_id=1), (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Kimura Defense to Guard',    'ESCAPE', 'Defender kimura desde side control y convertirla en oportunidad de recuperar guardia.',                                                'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Bottom Side Control'    AND owner_id=1), (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Knee On Belly Escape',       'ESCAPE', 'Escapar de knee on belly: crear espacio, introducir guardia o rodar hacia los pies del oponente.',                                     'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Bottom Knee On Belly'   AND owner_id=1), (SELECT id FROM position WHERE name='Half Guard'        AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Armbar Defense',             'ESCAPE', 'Defender el armbar: stacking, voltear, interlazar los dedos. Recuperar guardia o posición top.',                                      'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'           AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Triangle Defense',           'ESCAPE', 'Defender el triángulo: stack + postura, voltear, salir hacia el pasador.',                                                            'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'           AND owner_id=1), (SELECT id FROM position WHERE name='Side Control'      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Heel Hook Defense',          'ESCAPE', 'Defensa urgente de heel hook: no rotar, alinear rodilla, escape vine o back step.',                                                   'PURPLE', 'NOGI', (SELECT id FROM position WHERE name='Leg Entanglement'       AND owner_id=1), (SELECT id FROM position WHERE name='Standing Neutral'  AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
