-- V206__seed_techniques_transitions.sql
-- 12 transiciones curadas (owner_id=1, visibilidad pública)

INSERT INTO technique (owner_id, name, category, description, minimum_belt, modality, start_position_id, end_position_id, visibility, created_at, updated_at, version) VALUES

(1, 'Mount to Back Take',          'TRANSITION', 'Tomar la espalda desde mount cuando el oponente se voltea intentando escapar. Seguir el movimiento.',                             'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Full Mount'         AND owner_id=1), (SELECT id FROM position WHERE name='Back Mount'                 AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Side Control to Mount',       'TRANSITION', 'Avanzar de side control a mount: knee slide, step over o técnica de rodilla.',                                                   'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Side Control'       AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'                 AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Side Control to Back Take',   'TRANSITION', 'Tomar la espalda desde side control cuando el oponente se voltea hacia la turtle.',                                              'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Side Control'       AND owner_id=1), (SELECT id FROM position WHERE name='Back Mount'                 AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Guard to Back Take',          'TRANSITION', 'Transición de cualquier guardia a toma de espalda. Desde closed guard, butterfly, X-guard.',                                     'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Closed Guard'       AND owner_id=1), (SELECT id FROM position WHERE name='Back Mount'                 AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Side Control to North-South', 'TRANSITION', 'Girar de side control a north-south para cambiar ángulo de ataque o presión.',                                                   'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Side Control'       AND owner_id=1), (SELECT id FROM position WHERE name='North South'                AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'DLR to Single Leg X',         'TRANSITION', 'Transición de DLR a SLX (ashi garami). Girar por debajo para re-enredar la pierna.',                                            'BLUE',   'BOTH', (SELECT id FROM position WHERE name='De La Riva Guard'   AND owner_id=1), (SELECT id FROM position WHERE name='Single Leg X'               AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Half Guard to Deep Half',     'TRANSITION', 'Hundirse bajo el oponente desde media guardia para llegar a deep half guard.',                                                   'BLUE',   'BOTH', (SELECT id FROM position WHERE name='Half Guard'         AND owner_id=1), (SELECT id FROM position WHERE name='Deep Half Guard'            AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Closed Guard to Butterfly',   'TRANSITION', 'Abrir la guardia cerrada y reconfigurar los ganchos para guardia mariposa.',                                                    'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Closed Guard'       AND owner_id=1), (SELECT id FROM position WHERE name='Butterfly Guard'            AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Mount to Knee On Belly',      'TRANSITION', 'Pasar de mount a knee on belly para cambiar el ángulo o presionar diferente.',                                                  'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Full Mount'         AND owner_id=1), (SELECT id FROM position WHERE name='Knee On Belly'              AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'North-South to Kimura Trap',  'TRANSITION', 'Desde north-south entrar al kimura trap para controlar el brazo y avanzar a mount o back.',                                     'BLUE',   'BOTH', (SELECT id FROM position WHERE name='North South'        AND owner_id=1), (SELECT id FROM position WHERE name='Full Mount'                 AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Ashi Garami to 50/50',        'TRANSITION', 'Desde ashi garami básico el oponente gira para crear la posición 50/50 simétrica.',                                             'PURPLE', 'NOGI', (SELECT id FROM position WHERE name='Single Leg X'       AND owner_id=1), (SELECT id FROM position WHERE name='50/50'                      AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(1, 'Turtle to Guard Recovery',    'TRANSITION', 'Desde turtle rodar hacia adelante para recuperar guardia antes de que el oponente tome la espalda.',                            'WHITE',  'BOTH', (SELECT id FROM position WHERE name='Turtle'             AND owner_id=1), (SELECT id FROM position WHERE name='Closed Guard'               AND owner_id=1), 'PUBLIC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
