CREATE INDEX IF NOT EXISTS idx_technique_owner ON technique(owner_id);
CREATE INDEX IF NOT EXISTS idx_technique_deleted_at ON technique(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_technique_family ON technique(family);
CREATE INDEX IF NOT EXISTS idx_exercise_owner ON exercise(owner_id);
CREATE INDEX IF NOT EXISTS idx_exercise_deleted_at ON exercise(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_exercise_category ON exercise(category);
CREATE INDEX IF NOT EXISTS idx_injury_owner ON injury(owner_id);
CREATE INDEX IF NOT EXISTS idx_injury_owner_status ON injury(owner_id, status);
CREATE INDEX IF NOT EXISTS idx_competition_log_owner_date ON competition_log(owner_id, event_date DESC);
CREATE INDEX IF NOT EXISTS idx_competition_log_deleted_at ON competition_log(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_competition_match_technique ON competition_match(submission_technique_id) WHERE submission_technique_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_study_plan_owner ON study_plan(owner_id);
CREATE INDEX IF NOT EXISTS idx_study_plan_deleted_at ON study_plan(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_study_block_plan ON study_block(study_plan_id);
CREATE INDEX IF NOT EXISTS idx_note_deleted_at ON note(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_training_session_deleted_at ON training_session(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_tst_technique ON training_session_technique(technique_id);
CREATE INDEX IF NOT EXISTS idx_system_anchor_position ON system(anchor_position_id) WHERE anchor_position_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_system_deleted_at ON system(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_ruleset_federation ON ruleset(federation_id);
CREATE INDEX IF NOT EXISTS idx_ruleset_technique_technique ON ruleset_technique(technique_id);
CREATE INDEX IF NOT EXISTS idx_upf_federation ON user_profile_federation(federation_id);
