ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS stripes SMALLINT CHECK (stripes BETWEEN 0 AND 4);
ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS weight NUMERIC(5, 2) CHECK (weight BETWEEN 30 AND 180);
